Repository TheAyes/Food-Buddy, pull requests merged in 2023-07, with the labels that each got.

#41 Suchleiste
  api/data/grocery-data.json
  client/.env
  client/.gitignore
  client/src/app.jsx
  client/src/components/ProductItems/ProductItems.jsx
  client/src/components/ProductItems/ProductItems.module.scss
  client/src/components/SearchBar/SearchBar.jsx
  client/src/components/SearchBar/SearchBar.module.scss
  client/src/data/data.json
  client/src/data/grocery-data.json
  client/src/global.scss
  client/src/pages/ItemList/ItemList.module.scss
  client/src/pages/ItemList/item-list.jsx
  client/src/variable.scss
  package-lock.json
  package.json
Labels: frontend, component

#36 goBack Button Styling
  client/src/app.jsx
  client/src/components/AddToCartComponent/AddToCartComponent.jsx
  client/src/components/AddToCartComponent/AddToCartComponent.module.scss
  client/src/components/GoBackButton/GoBackButton.jsx
  client/src/components/GoBackButton/GoBackButton.module.scss
  client/src/pages/DetailsPage/item-details.jsx
  client/src/pages/DetailsPage/item-details.module.scss
  client/src/pages/WishList/wishlist-page.jsx
  client/src/variable.scss
Labels: frontend, component

#45 landingpage + landpagetwo
  client/src/app.jsx
  client/src/pages/LandPageTwo/land-page-two.jsx
  client/src/pages/LandPageTwo/landPageTwo.module.scss
  client/src/pages/Landingpage/landing-page.jsx
  client/src/pages/Landingpage/landingPage.module.scss
  client/src/pics/LogoGreen.svg
  client/src/pics/LogoWhite.svg
  package-lock.json
  package.json
Labels: frontend

#48 Fixes everywhere
  .idea/inspectionProfiles/Project_Default.xml
  client/package-lock.json
  client/package.json
  client/src/app.jsx
  client/src/pages/ItemList/item-list.jsx
  client/src/pages/Login/Login.jsx
  client/src/pages/Login/Login.module.scss
  client/src/pages/Profil/profile-page.jsx
  client/src/pages/Profil/profile-page.module.scss
  client/src/pages/Register/Register.module.scss
  client/src/pics/edit_FILL0_wght700_GRAD0_opsz48.svg
Labels: bug, enhancement, frontend, component, page
