Repository TheAyes/Food-Buddy, pull requests merged in 2023-06, with the labels that each got.

#26 Category site
  client/src/app.jsx
  client/src/components/CartItem/CartItem.jsx
  client/src/components/CategoryBar/CategoryBar.jsx
  client/src/components/CategoryBarImage/CategoryBarImage.jsx
  client/src/components/Grocery/GroceryDeals.jsx
  client/src/components/MemberDeals/MemberDeals.jsx
  client/src/components/NavBar/NavBar.jsx
  client/src/components/OrderHistoryItems/OrderHistoryItems.jsx
  client/src/components/ProductItems/ProductItems.jsx
  client/src/components/RabattBar/RabattBar.jsx
  client/src/components/SearchBar/SearchBar.jsx
  client/src/components/WishItem/WishItem.jsx
  client/src/data/data.json
  client/src/pages/DetailsPage/item-details.jsx
  client/src/pages/Filter/filter-page.jsx
  client/src/pages/Homepage/home-page.jsx
  client/src/pages/ItemList/item-list.jsx
  client/src/pages/Landingpage/landing-page.jsx
  client/src/pages/MyCartPage/cart-page.jsx
  client/src/pages/NotFound/not-found.jsx
  client/src/pages/OrderHistory/order-history-page.jsx
  client/src/pages/Profil/profile-page.jsx
  client/src/pages/WishList/wishlist-page.jsx
Labels: frontend, page

#25 16 detailseite produkt
  client/src/app.jsx
  client/src/components/GoBackButton/GoBackButton.jsx
  client/src/fonts/Roboto/LICENSE.txt
  client/src/fonts/Roboto/Roboto-Black.ttf
  client/src/fonts/Roboto/Roboto-BlackItalic.ttf
  client/src/fonts/Roboto/Roboto-Bold.ttf
  client/src/fonts/Roboto/Roboto-BoldItalic.ttf
  client/src/fonts/Roboto/Roboto-Italic.ttf
  client/src/fonts/Roboto/Roboto-Light.ttf
  client/src/fonts/Roboto/Roboto-LightItalic.ttf
  client/src/fonts/Roboto/Roboto-Medium.ttf
  client/src/fonts/Roboto/Roboto-MediumItalic.ttf
  client/src/fonts/Roboto/Roboto-Regular.ttf
  client/src/fonts/Roboto/Roboto-Thin.ttf
  client/src/fonts/Roboto/Roboto-ThinItalic.ttf
  client/src/global.scss
  client/src/pages/DetailsPage/item-details.jsx
  client/src/pages/DetailsPage/item-details.module.scss
  client/src/pages/ItemList/item-list.jsx
  client/src/variable.scss
Labels: frontend

#30 font family eingebaut
  client/package-lock.json
  client/package.json
  client/src/fonts/Roboto/LICENSE.txt
  client/src/fonts/Roboto/Roboto-Black.ttf
  client/src/fonts/Roboto/Roboto-BlackItalic.ttf
  client/src/fonts/Roboto/Roboto-Bold.ttf
  client/src/fonts/Roboto/Roboto-BoldItalic.ttf
  client/src/fonts/Roboto/Roboto-Italic.ttf
  client/src/fonts/Roboto/Roboto-Light.ttf
  client/src/fonts/Roboto/Roboto-LightItalic.ttf
  client/src/fonts/Roboto/Roboto-Medium.ttf
  client/src/fonts/Roboto/Roboto-MediumItalic.ttf
  client/src/fonts/Roboto/Roboto-Regular.ttf
  client/src/fonts/Roboto/Roboto-Thin.ttf
  client/src/fonts/Roboto/Roboto-ThinItalic.ttf
  client/src/global.scss
  client/src/main.jsx
  client/src/pages/DetailsPage/item-details.jsx
  client/src/pages/DetailsPage/item-details.module.scss
  client/src/variable.scss
  package-lock.json
  package.json
Labels: frontend

#28 NavBar Vers.1
  client/src/app.jsx
  client/src/components/NavBar/NavBar.jsx
  client/src/components/NavBar/NavBar.module.scss
Labels: frontend, component
